# Generated by Django 3.0.6 on 2020-05-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='message',
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet',
            field=models.TextField(default='Thsi is a Test, Do not attempt to change the string', max_length=140),
            preserve_default=False,
        ),
    ]
